### PR TITLE
Exception deriving fixes

### PR DESCRIPTION
**Pull request by gquemener**

### CODE REVIEW

**Comment by gquemener** [comment]
See https://github.com/prolic/fpp/pull/85#discussion_r230636647 regarding the `is_a` usage please

**Comment by prolic** [comment]
@gquemener merged, but...
`is_a` is deprecated by PHP, so there is no reason at all to use a deprecated function. Maybe you are looking for `is_subclass_of`?

**Comment by prolic** [comment]
Just read your other comment, sorry, my bad :)

**Comment by gquemener** [comment]
No worry,

Undeprecated functions are quite unusual to be fair!

**Pull request merged**
