### PR TITLE
fix to/from-array builders

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by prolic** [comment]
ping @Adirelle

**Comment by Adirelle** [comment]
Pong! I'll give it a try.

**Comment by Adirelle** [comment]
Almost. See https://github.com/prolic/fpp/commit/4427acd66799922ea3071465c3131cf521bacd4b. 

`\$this->$argumentName` can be null so you cannot use it directly in `foreach`. I lazily fixed it using an `(array)` typecast but a null check could also work, though the indentation has to be changed.

**Comment by Adirelle** [comment]
Fixed it. Thank you.

**Comment by prolic** [comment]
thanks @Adirelle

**Pull request merged**
