### PR TITLE
allow list + nullable + allow fromString for objects of objects representing strings

### PR DESCRIPTION
**Pull request by prolic**
fixes https://github.com/prolic/fpp/issues/43
fixes https://github.com/prolic/fpp/issues/44

ping @Maikel-Koek - can you check this PR?

### CODE REVIEW

**Comment by Maikel-Koek** [comment]
I will check!
Did you also notice my last comment on https://github.com/prolic/fpp/issues/42#issuecomment-389069293?

**Comment by prolic** [comment]
yes, just pushed a fix

**Comment by prolic** [comment]
@paales this PR also fixes https://github.com/prolic/fpp/issues/46

**Comment by paales** [comment]
Not sure if the code can be tested yet, but just did.


```fpp
namespace MyNamespace {
    data ExternalId = Int deriving(FromScalar, ToScalar, Equals);
}
```

Results in invalid code:

```
namespace MyNamespace;

final class ExternalId
{
....

    public static function fromScalar(int ${{argument_name}}): ExternalId
    {
    }


}
```

Argument name isn't properly replaced.

**Comment by Maikel-Koek** [comment]
Just generated the models with this branch, gives a couple of errors, for example:
> ParseError: syntax error, unexpected '$', expecting variable (T_VARIABLE)
```
    public static function fromScalar(int ${{argument_name}}): StoreId
    {
    }
```
Instead of:
```
    public static function fromScalar(int $storeId): StoreId
    {
        return new StoreId($storeId);
    }
```

**Comment by prolic** [comment]
Thanks, I know what's going on. I missed the scalar constructors. Will
provide a fix with further tests in 1-2 hours.

**Comment by prolic** [comment]
@paales @Maikel-Koek this should work with the latest commit now, also added further tests for this use-case.

**Comment by Maikel-Koek** [comment]
Seems to be working!

**Comment by Maikel-Koek** [comment]
@prolic:
Still a small bug found:

```
    public function termPrices(): ?array
    {
        if (! isset($this->termPrices) && isset($this->payload['termPrices'])) {
            $__returnValue = [];

            foreach ($this->payload['termPrices'] as $__value) {
                $__returnValue = \ReachDigital\Subscription\Model\ProductPlan\TermPrice::fromArray($__value);
            }

            $this->termPrices = $__returnValue;
        }

        return $this->termPrices;
```

`$__returnValue` in the foreach-loop should be `$__returnValue[]`

**Comment by prolic** [comment]
@Maikel-Koek thanks, fixed in master branch, I also added another batch of tests, so this doesn't come up again.

**Pull request merged**
