### PR TITLE
initialise arrays in constructors (fixes #90)

### LINKED ISSUE #90: Arrays in constructor raise errors on withMyArrayValue if the array is empty
```
data Person = Person { string $name, string[] $habits };
```

creates 

```php
final class Person
{
    private $name;
    private $habits;

    public function __construct(string $name, array $habits)
    {
        $this->name = $name;
        foreach ($habits as $__value) {
            if (! \is_string($__value)) {
                throw new \InvalidArgumentException('habits expected an array of string');
            }
            $this->habits[] = $__value;
        }
    }
```

What is missed in `__construct`:

```php
$this->habits = [];
```

### PR DESCRIPTION
**Pull request by ronnyhartenstein**

### CODE REVIEW

**Comment by prolic** [comment]
thanks for the PR. some tests are failing on travis, can you check?

**Comment by ronnyhartenstein** [comment]
Ok, I'll check it soon. Maybe a test has to be adjusted or so.
(Sorry, I'm a bit busy last few days with a project at work, but hey, it's a pleasure to use your tool for it 👍 )

**Comment by prolic** [comment]
thank you!

**Comment by ronnyhartenstein** [comment]
Thank you for your great tool! I hope it'll gain the attraction it deserves..

**Pull request merged**
